### ISSUE TITLE
Remove the installation of curl and use nc for health checks

### ISSUE THREAD

**Issue by Cooryd** [libero/audit#19]
Remove this line:

https://github.com/libero/audit/blob/1c1fb36faa4d5aaf2e6612a0c33b81925e9b8ef6/Dockerfile#L32

docker-compose configs can be updated to use something like: 
```
 test: 'echo -e "GET /health\n\n" | nc localhost ${AUTHENTICATION_PORT:-3001}'
```

https://github.com/libero/audit/blob/1c1fb36faa4d5aaf2e6612a0c33b81925e9b8ef6/docker-compose.test.yml#L11

https://github.com/libero/audit/blob/1c1fb36faa4d5aaf2e6612a0c33b81925e9b8ef6/docker-compose.yml#L9

**Comment by diversemix** [comment]
Cloned into reviewer
