### ISSUE TITLE
Change code to conform to original xpub schema

### ISSUE THREAD

**Issue by erezmus** [libero/audit#21]
Currently, audit uses a new schema for storing audit logs but this clashes with the requirement that we keep the current xpub schema and the data in one database.

- [x] Change code to conform to old xpub
- [x] Comment out migrations as we don't want to accidentally run migrations
- [ ] Use the xpub postgres image for integration tests (liberoadmin/reviewer-xpub-postgres)

**Comment by erezmus** [comment]
So one of the issue i've come across with the xpub schema postgres container is that it has foreign key constraints between tables. For example audit_log  has a foreign key constraint with the id column of the user table. When adding a log item that the user is logged in, it results in an error because the user might not have been added yet.

As we will be moving to multiple databases eventually, we will need to break off those constraints between tables that will eventually live in separate databases.

For now i suggest remove the constraint from the schema file and also remove it in xpub

**Comment by diversemix** [comment]
Just talked about this - we are also changing `user_id` from type UUID to text (as its currently not used)

**Comment by erezmus** [comment]
https://github.com/elifesciences/elife-xpub/issues/2409
